---
homebrew_packages:
  - coreutils
  - moreutils
  - git
  - tmux
  - vim
  - neovim
  - asdf
  - gnupg
  - pinentry-mac
  - tig
  - tio
  - dockutil

homebrew_cask_packages:
  - firefox
  - alfred
  - iterm2
  - caffeine
  - font-jetbrains-mono-nerd-font

linux_packages:
  - apt-transport-https
  - binutils
  - cron
  - curl
  - debconf-utils
  - debian-goodies
  - dnsutils
  - gnupg
  - git
  - hdparm
  - locales
  - lsb-release
  - lsof
  - rsyslog
  - rsync
  - screen
  - sudo
  - unzip
  - python3-pip
  - python3-setuptools
  - neovim
  - net-tools
  - kbd
