---
- name: Gather facts
  setup:

- name: Download dotfiles
  git:
    repo: "https://github.com/GonzaloAlvarez/dotfiles.git"
    dest: "{{ ansible_facts['env'].HOME }}/.dotfiles"

- name: Download gear repo
  git:
    repo: 'https://github.com/GonzaloAlvarez/gear.git'
    dest: '{{ ansible_facts["env"].HOME }}/.gear'

- name: Install dotfiles
  ansible.builtin.shell:
    cmd: "./setup"
    chdir: "{{ ansible_facts['env'].HOME }}/.dotfiles/"

- name: Execute osx specific tasks
  ansible.builtin.include_tasks: osx_iterm.yml
  when: ansible_facts['os_family'] == "Darwin"
